In [2]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt

In [26]:
anime = pd.read_csv('data/anime.csv')
rating = pd.read_csv('data/rating.csv')

In [29]:
anime = anime[anime['type'] != 'Music']
anime = anime[anime['genre'].str.contains('Hentai') == False]
anime = anime[pd.notnull(anime['type'])]

In [33]:
display(rating)

         user_id  anime_id  rating
0              1        20      -1
1              1        24      -1
2              1        79      -1
3              1       226      -1
4              1       241      -1
5              1       355      -1
6              1       356      -1
7              1       442      -1
8              1       487      -1
9              1       846      -1
10             1       936      -1
11             1      1546      -1
12             1      1692      -1
13             1      1836      -1
14             1      2001      -1
15             1      2025      -1
16             1      2144      -1
17             1      2787      -1
18             1      2993      -1
19             1      3455      -1
20             1      4063      -1
21             1      4214      -1
22             1      4224      -1
23             1      4581      -1
24             1      4744      -1
25             1      4898      -1
26             1      4999      -1
27             1      5034      -1
28             1      5277      -1
29             1      5667      -1
...          ...       ...     ...
7813707    73515     10490       6
7813708    73515     10588       9
7813709    73515     11021       8
7813710    73515     11111       8
7813711    73515     11241       8
7813712    73515     11411       5
7813713    73515     11701       7
7813714    73515     11741       9
7813715    73515     11751       6
7813716    73515     11757       9
7813717    73515     11759       8
7813718    73515     11837       9
7813719    73515     12031       8
7813720    73515     12113      10
7813721    73515     12115      10
7813722    73515     12293       8
7813723    73515     12413       9
7813724    73515     12445       8
7813725    73515     12461       7
7813726    73515     12967       7
7813727    73515     13161       8
7813728    73515     13331       9
7813729    73515     13599       7
7813730    73515     13659       8
7813731    73515     14345       7
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

[7813737 rows x 3 columns]

In [18]:
rating = rating.dropna()
rating = rating[rating['rating']>-1]

In [19]:
display(rating)

         user_id  anime_id  rating
47             1      8074      10
81             1     11617      10
83             1     11757      10
101            1     15451      10
153            2     11771      10
156            3        20       8
157            3       154       6
158            3       170       9
159            3       199      10
160            3       225       9
161            3       341       6
162            3       430       7
163            3       527       7
164            3       552       7
165            3       813      10
166            3      1119       7
167            3      1121       7
168            3      1122       7
169            3      1132       8
170            3      1292       6
171            3      1313       8
172            3      1526       7
173            3      1535      10
174            3      1564       7
175            3      1689       8
176            3      1764       6
177            3      1943       8
178            3      2201       7
179            3      2404       7
180            3      2847       7
...          ...       ...     ...
7813707    73515     10490       6
7813708    73515     10588       9
7813709    73515     11021       8
7813710    73515     11111       8
7813711    73515     11241       8
7813712    73515     11411       5
7813713    73515     11701       7
7813714    73515     11741       9
7813715    73515     11751       6
7813716    73515     11757       9
7813717    73515     11759       8
7813718    73515     11837       9
7813719    73515     12031       8
7813720    73515     12113      10
7813721    73515     12115      10
7813722    73515     12293       8
7813723    73515     12413       9
7813724    73515     12445       8
7813725    73515     12461       7
7813726    73515     12967       7
7813727    73515     13161       8
7813728    73515     13331       9
7813729    73515     13599       7
7813730    73515     13659       8
7813731    73515     14345       7
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

[6337241 rows x 3 columns]

In [12]:
user_grouped = rating.groupby(rating['user_id']).agg({'anime_id':'count'})